api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('posts', views.PostViewSet, basename='posts')
router.register('users', views.UserViewSet, basename='users')

urlpatterns = router.urls + [
    path('current-user/', views.CurrentUserView.as_view())
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

api/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(get_user_model(), related_name='posts', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    
    def __str__(self):
        return self.username

users/forms.py
from tkinter import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = CustomUser
        fields = ('username', 'email')
        
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')
        

api/views.py
from rest_framework import generics, viewsets, permissions
from django.contrib.auth import get_user_model


from posts.models import Post
from .serializers import PostSerializer, UserSerializer
from .permissions import IsAuthorOrReadOnly

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    # permission_classes = [IsAuthorOrReadOnly]
    permission_classes = [permissions.IsAuthenticated]
    
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    
class CurrentUserView(generics.RetrieveAPIView):
    serializer_class = UserSerializer
    def get_object(self):
        return self.request.user

posts/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/home.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/ff1d9ad615.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />


    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">

</head>


<body>
    {% csrf_token %}
    <main>
        <div id="app">
            <div class="container">
                <navbar></navbar>
            </div>
            <div class="container" v-if="!create" style="height: 90vh;">
                <div class="row">
                    <div>
                        <div v-for='post in posts' :key="post.id" class="card mx-auto m-4" style="width: 22rem;">
                            <div class="card-body p-0">
                                <h5 class="card-title p-2">[[ post.title ]]</h5>
                                <h6 class="card-subtitle mb-2 text-muted p-2 text-capitalize">[[
                                    post.author_detail.username ]]</h6>
                                <p class="card-text px-2">[[ post.body ]]</p>
                                <p class="card-text text-end px-2"><i class="fa-solid fa-trash edit mx-3 text-danger"
                                        @click='editPost(post.id)'></i><i
                                        class="fa-sharp fa-solid fa-pencil text-primary edit"></i></p>
                                <div class="card-footer text-muted text-capitalize fst-italic text-end">
                                    Posted: [[ post.updated | formatTime ]]
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container" v-if="edit" style="height: 90vh;">
                <div class="row">
                    <div class="card mx-auto m-4" style="width: 22rem;">
                        <div class="card-body p-0">
                            <h5 class="card-title p-2">[[ post.title ]]</h5>
                            <h6 class="card-subtitle mb-2 text-muted p-2 text-capitalize">[[
                                post.author_detail.username ]]</h6>
                            <p class="card-text px-2">[[ post.body ]]</p>
                            <p class="card-text text-end px-2"><i class="fa-solid fa-trash edit mx-3 text-danger"></i>
                            <div class="card-footer text-muted text-capitalize fst-italic text-end">
                                Posted: [[ post.updated | formatTime ]]
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container d-flex align-items-center justify-content-center" v-if="create" style="height: 50vh;">
                <div class="mb-5">
                    <template v-if="postErrors.body">
                        <p class="text-center text-danger text-uppercase" v-for="error in postErrors.body">[[ error ]]
                        </p>
                    </template>
                    <div class="row">
                        <div class="">
                            <input type="text" class="form-control form-control-lg shadow-none" placeholder="Title"
                                v-model="newPost.title">
                        </div>
                    </div>
                    <div class="row">
                        <div class="">
                            <textarea type="text" class="form-control form-control-lg shadow-none mt-4"
                                placeholder="Message..." v-model="newPost.body"></textarea>
                        </div>
                    </div>
                    <button class="btn btn-primary d-inline d-block mx-auto mt-2" @click="createPost">Post</button>
                </div>
            </div>
        </div>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="{% static '/app.js' %}"></script>
</body>

</html>

templates/partials/_navbar.html
{% load static %}

<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="/static/images/icons8-osprey-50.png" alt="">
    </a>
    <ul class="nav my-auto">
        {% if user.is_authenticated %}
        <a class="nav-link text-decoration-none text-capitalize px-0">Welcome, {{user.username}}!</a>
        <create></create>
        <!-- <a class="nav-link text-decoration-none text-capitalize" role="button"  @click='create=true'>+ New Post</a> -->
        <a class="nav-link text-decoration-none text-u" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
        <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link">Signup</a></li>
        {% endif %}
    </ul>
</header>